export const COUNTRY = [
  { key: 'kr', display: 'KR', region: 'kr' },
  { key: 'jp', display: 'JP', region: 'jp1' },
  { key: 'ph', display: 'PH', region: 'ph2' },
  { key: 'sg', display: 'SG', region: 'sg2' },
  { key: 'th', display: 'TH', region: 'th2' },
  { key: 'tw', display: 'TW', region: 'tw2' },
  { key: 'vn', display: 'VN', region: 'vn2' },
  { key: 'na', display: 'NA', region: 'na1' },
  { key: 'br', display: 'BR', region: 'br1' },
  { key: 'lan', display: 'LAN', region: 'la1' },
  { key: 'las', display: 'LAS', region: 'la2' },
  { key: 'oce', display: 'OCE', region: 'oc1' },
  { key: 'euw', display: 'EUW', region: 'euw1' },
  { key: 'eune', display: 'EUNE', region: 'eun1' },
  { key: 'ru', display: 'RU', region: 'ru' },
  { key: 'tr', display: 'TR', region: 'tr1' },
];
